apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: url-mapper-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.1
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: url-mapper-rs
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
