[package]
name = "adder"
version = "0.1.0"
authors = ["JasonkayZK <271226192@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
add-one = { path = "../add-one" }
rand = "0.8.3"